workflows:
  ios-workflow:
    name: Build IRIS
    environment:
      xcode: latest
    scripts:
      - name: Build .ipa
        script: |
          xcodebuild -project IRIS.xcodeproj \
                     -scheme IRIS \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     clean archive -archivePath $CM_BUILD_DIR/IRIS.xcarchive

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/IRIS.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - ipa/*.ipa
