workflows:
  ios-workflow:
    name: Build IRIS-MALL
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          echo "No dependencies to install"
      - name: Build .ipa
        script: |
          xcodebuild -project IRIS-MALL.xcodeproj \
                     -scheme IRIS-MALL \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     clean archive -archivePath $CM_BUILD_DIR/IRIS-MALL.xcarchive

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/IRIS-MALL.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - build/ios/ipa/*.ipa
